-- CreateTable
CREATE TABLE "SampleData" (
    "id" TEXT NOT NULL,
    "LogTime" TIMESTAMP(3) NOT NULL,
    "Pkt_Hdr" TEXT NOT NULL,
    "RSU_ID" INTEGER NOT NULL,
    "OBU_ID" INTEGER NOT NULL,
    "PktType" INTEGER NOT NULL,
    "PktLen" INTEGER NOT NULL,
    "Time(IST)" TIMESTAMP(3) NOT NULL,
    "GPSValid" TEXT NOT NULL,
    "Latitude" DOUBLE PRECISION NOT NULL,
    "Longitude" DOUBLE PRECISION NOT NULL,
    "Date(IST)" TIMESTAMP(3) NOT NULL,
    "Accel_X" DOUBLE PRECISION NOT NULL,
    "Accel_Y" DOUBLE PRECISION NOT NULL,
    "Accel_Z" DOUBLE PRECISION NOT NULL,
    "Gyro_X" DOUBLE PRECISION NOT NULL,
    "Gyro_Y" DOUBLE PRECISION NOT NULL,
    "Gyro_Z" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "SampleData_pkey" PRIMARY KEY ("id")
);
